--
-- Creating table TB_M_GEOGRAPHY
-- ===============================
--

CREATE TABLE "TB_M_GEOGRAPHY" (
"GEO_ID" NUMBER (5) NOT NULL,
"GEO_NAME" NVARCHAR2 (255) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_GEOGRAPHY ADD CONSTRAINT PK_M_GEOGRAPHY PRIMARY KEY (GEO_ID ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_PROVINCE
-- ===============================
--

CREATE TABLE "TB_M_PROVINCE" (
"PROVINCE_CODE" VARCHAR2 (2) NOT NULL,
"PROVINCE_NAME" NVARCHAR2 (150) NOT NULL,
"PROVINCE_NAME_ENG" VARCHAR2 (150) NOT NULL,
"GEO_ID" NUMBER (5) DEFAULT '0' NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_PROVINCE ADD CONSTRAINT PK_M_PROVINCE PRIMARY KEY (PROVINCE_CODE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_M_PROVINCE1 on TB_M_PROVINCE (GEO_ID)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_M_PROVINCE2 on TB_M_PROVINCE (GEO_ID, PROVINCE_CODE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_M_AMPHUR
-- ===============================
--

CREATE TABLE "TB_M_AMPHUR" (
"AMPHUR_CODE" VARCHAR2 (4) NOT NULL,
"AMPHUR_NAME" NVARCHAR2 (150) NOT NULL,
"AMPHUR_NAME_ENG" VARCHAR2 (150) NOT NULL,
"GEO_ID" NUMBER (5) DEFAULT '0' NOT NULL,
"PROVINCE_CODE" VARCHAR2 (2) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 92K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_AMPHUR ADD CONSTRAINT PK_M_AMPHUR PRIMARY KEY (AMPHUR_CODE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 92K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_M_AMPHUR1 on TB_M_AMPHUR (PROVINCE_CODE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 92K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_M_AMPHUR2 on TB_M_AMPHUR (PROVINCE_CODE, AMPHUR_CODE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 92K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_M_AMPHUR3 on TB_M_AMPHUR (GEO_ID, PROVINCE_CODE, AMPHUR_CODE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 92K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_M_DISTRICT
-- ===============================
--

CREATE TABLE "TB_M_DISTRICT" (
"DISTRICT_CODE" VARCHAR2 (6) NOT NULL,
"DISTRICT_NAME" NVARCHAR2 (150) NOT NULL,
"DISTRICT_NAME_ENG" VARCHAR2 (150) NOT NULL,
"AMPHUR_CODE" VARCHAR2 (4) NOT NULL,
"PROVINCE_CODE" VARCHAR2 (2) NOT NULL,
"GEO_ID" NUMBER (5) DEFAULT '0' NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 1024K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_DISTRICT ADD CONSTRAINT PK_M_DISTRICT PRIMARY KEY (DISTRICT_CODE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 1024K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_M_DISTRICT1 on TB_M_DISTRICT (PROVINCE_CODE, AMPHUR_CODE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 1024K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_M_DISTRICT2 on TB_M_DISTRICT (PROVINCE_CODE, AMPHUR_CODE, DISTRICT_CODE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 1024K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_M_DISTRICT3 on TB_M_DISTRICT (GEO_ID, PROVINCE_CODE, AMPHUR_CODE, DISTRICT_CODE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 1024K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_M_ZIPCODES
-- ===============================
--

CREATE TABLE "TB_M_ZIPCODES" (
"ZIPCODE" VARCHAR2 (11) NOT NULL,
"DISTRICT_CODE" VARCHAR2 (6) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_ZIPCODES ADD CONSTRAINT PK_M_ZIPCODES PRIMARY KEY (ZIPCODE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_M_ZIPCODES1 on TB_M_ZIPCODES (DISTRICT_CODE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_M_DEALER
-- ===============================
--

CREATE TABLE "TB_M_DEALER" (
"DEALER_CD" VARCHAR2 (20) NOT NULL,
"DEALER_NAME" NVARCHAR2 (30) NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_DEALER ADD CONSTRAINT PK_M_DEALER PRIMARY KEY (DEALER_CD , DEALER_NAME ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_VEHICLE
-- ===============================
--

CREATE TABLE "TB_M_VEHICLE" (
"VEH_BRAND" VARCHAR2 (50) NOT NULL,
"VEH_VIN_NO" VARCHAR2 (20) NOT NULL,
"VEH_SERIES" VARCHAR2 (30) NOT NULL,
"VEH_MODEL" VARCHAR2 (6) NOT NULL,
"VEH_COLOR" VARCHAR2 (5) NOT NULL,
"VEH_YEAR" VARCHAR2 (4) NOT NULL,
"VEH_REG_NO" VARCHAR2 (20) NOT NULL,
"VEH_ENGINE" VARCHAR2 (20) NOT NULL,
"VEH_WEIGHT" VARCHAR2 (20) NOT NULL,
"VEH_CC" TIMESTAMP  NOT NULL,
"VEH_TYPE" VARCHAR2 (20) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_VEHICLE ADD CONSTRAINT PK_M_VEHICLE PRIMARY KEY (VEH_BRAND , VEH_VIN_NO ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_CUSTOMER_PERSONAL
-- ===============================
--

CREATE TABLE "TB_M_CUSTOMER_PERSONAL" (
"ID_CARD" VARCHAR2 (20) NOT NULL,
"MOBILE" VARCHAR2 (100) NOT NULL,
"TITLE1" NVARCHAR2 (100) NOT NULL,
"TITLE2" NVARCHAR2 (100) NOT NULL,
"FIRST_NAME" NVARCHAR2 (100) NOT NULL,
"LAST_NAME" NVARCHAR2 (100) NOT NULL,
"GENDER" NVARCHAR2 (100),
"BIRTH_DATE" VARCHAR2 (100),
"ADDRESS1" NVARCHAR2 (100),
"ADDRESS2" NVARCHAR2 (100),
"PROVINCE" NVARCHAR2 (100),
"DISTRICT" NVARCHAR2 (100),
"SUB_DISTRICT" NVARCHAR2 (100),
"ZIPCODE" VARCHAR2 (100),
"TELEPHONE" VARCHAR2 (100),
"EMAIL" VARCHAR2 (100),
"LINE_NO" VARCHAR2 (100),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_CUSTOMER_PERSONAL ADD CONSTRAINT PK_M_CUSTOMER_PERSONAL PRIMARY KEY (ID_CARD ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_CUSTOMER_COMPANY
-- ===============================
--

CREATE TABLE "TB_M_CUSTOMER_COMPANY" (
"TAX_ID" VARCHAR2 (20) NOT NULL,
"PHONE" VARCHAR2 (100) NOT NULL,
"COMPANY_NAME" NVARCHAR2 (100) NOT NULL,
"BRANCH_NO" NVARCHAR2 (100) NOT NULL,
"REGISTER_DATE" VARCHAR2 (100) NOT NULL,
"FIRST_NAME" NVARCHAR2 (100) NOT NULL,
"LAST_NAME" NVARCHAR2 (100),
"ADDRESS1" NVARCHAR2 (100),
"ADDRESS2" NVARCHAR2 (100),
"PROVINCE" NVARCHAR2 (100),
"DISTRICT" NVARCHAR2 (100),
"SUB_DISTRICT" NVARCHAR2 (100),
"ZIPCODE" VARCHAR2 (100),
"MOBILE" VARCHAR2 (100),
"EMAIL" VARCHAR2 (100),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_CUSTOMER_COMPANY ADD CONSTRAINT PK_M_CUSTOMER_COMPANY PRIMARY KEY (TAX_ID ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_INSURANCE
-- ===============================
--

CREATE TABLE "TB_M_INSURANCE" (
"INS_CODE" VARCHAR2 (20) NOT NULL,
"INS_NAME" NVARCHAR2 (100) NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_INSURANCE ADD CONSTRAINT PK_M_INSURANCE PRIMARY KEY (INS_CODE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_R_CAR_INSURANCE
-- ===============================
--

CREATE TABLE "TB_R_CAR_INSURANCE" (
"DOCUMENT_NO" VARCHAR2 (10) NOT NULL,
"DOCUMENT_STATUS" VARCHAR2 (2),
"VEH_BRAND" VARCHAR2 (50) NOT NULL,
"VEH_VIN_NO" VARCHAR2 (20) NOT NULL,
"VEH_SERIES" VARCHAR2 (30),
"VEH_MODEL" VARCHAR2 (6),
"VEH_COLOR" VARCHAR2 (5),
"VEH_YEAR" VARCHAR2 (4),
"VEH_REG_NO" VARCHAR2 (100),
"VEH_ENGINE" VARCHAR2 (20),
"VEH_WEIGHT" VARCHAR2 (20),
"VEH_CC" VARCHAR2 (20),
"VEH_TYPE" VARCHAR2 (20),
"FIN_TYPE_PURCHASE" VARCHAR2 (1) NOT NULL,
"FIN_LEASING_COMPANY" VARCHAR2 (20) NOT NULL,
"INS_CHOICE" VARCHAR2 (20),
"INS_COMPANY" VARCHAR2 (20),
"INS_CLASS" VARCHAR2 (20),
"INS_TYPE" VARCHAR2 (20),
"INS_PREMIUM_TYPE" VARCHAR2 (20),
"INS_COVERAGE_YEAR" VARCHAR2 (20),
"INS_PREMIUM" NUMBER (10,0),
"INS_COVERAGE" NUMBER (10,0),
"INS_ACT" NUMBER (5,2),
"INS_ACTIVATION_DATE" DATE ,
"INS_COVERAGE_DATE" DATE ,
"INS_POLICY_NO" VARCHAR2 (20),
"INS_TEMP_POLICY_NO" VARCHAR2 (20),
"INS_REMARK" NVARCHAR2 (2000),
"CUS_TYPE" VARCHAR2 (1),
"CUS_POLICY_DELIVERY" VARCHAR2 (1),
"CUS_P_ID_CARD" VARCHAR2 (20),
"CUS_P_MOBILE" VARCHAR2 (20),
"CUS_P_TITLE1" NVARCHAR2 (20),
"CUS_P_TITLE2" NVARCHAR2 (20),
"CUS_P_FIRST_NAME" NVARCHAR2 (20),
"CUS_P_LAST_NAME" NVARCHAR2 (20),
"CUS_P_GENDER" VARCHAR2 (1),
"CUS_P_BIRTH_DATE" DATE ,
"CUS_P_ADDRESS1" NVARCHAR2 (200),
"CUS_P_ADDRESS2" NVARCHAR2 (200),
"CUS_P_PROVINCE" NVARCHAR2 (20),
"CUS_P_DISTRICT" NVARCHAR2 (20),
"CUS_P_SUB_DISTRICT" NVARCHAR2 (20),
"CUS_P_ZIPCODE" VARCHAR2 (5),
"CUS_P_TELEPHONE" VARCHAR2 (20),
"CUS_P_SAME_ADDRESS_FLAG" VARCHAR2 (1),
"CUS_P_BILL_ADDRESS1" NVARCHAR2 (200),
"CUS_P_BILL_ADDRESS2" NVARCHAR2 (200),
"CUS_P_BILL_PROVINCE" NVARCHAR2 (20),
"CUS_P_BILL_DISTRICT" NVARCHAR2 (20),
"CUS_P_BILL_SUB_DISTRICT" NVARCHAR2 (20),
"CUS_P_BILL_ZIPCODE" VARCHAR2 (5),
"CUS_P_BENEFICIARY" NVARCHAR2 (20),
"CUS_P_REF_TEL_NO" VARCHAR2 (20),
"CUS_P_LINE_ID" VARCHAR2 (20),
"CUS_P_EMAIL" VARCHAR2 (20),
"CUS_C_TAX_ID" VARCHAR2 (20),
"CUS_C_PHONE" VARCHAR2 (20),
"CUS_COMPANY_NAME" NVARCHAR2 (20),
"CUS_C_BRANCH_NO" NVARCHAR2 (20),
"CUS_C_REGISTER_DATE" VARCHAR2 (20),
"CUS_C_FIRST_NAME" NVARCHAR2 (20),
"CUS_C_LAST_NAME" NVARCHAR2 (20),
"CUS_C_ADDRESS1" NVARCHAR2 (200),
"CUS_C_ADDRESS2" NVARCHAR2 (200),
"CUS_C_PROVINCE" NVARCHAR2 (20),
"CUS_C_DISTRICT" NVARCHAR2 (20),
"CUS_C_SUB_DISTRICT" NVARCHAR2 (20),
"CUS_C_ZIPCODE" VARCHAR2 (5),
"CUS_C_MOBILE" VARCHAR2 (20),
"CUS_C_SAME_ADDRESS_FLAG" VARCHAR2 (1),
"CUS_C_BILL_ADDRESS1" NVARCHAR2 (200),
"CUS_C_BILL_ADDRESS2" NVARCHAR2 (200),
"CUS_C_BILL_PROVINCE" NVARCHAR2 (20),
"CUS_C_BILL_DISTRICT" NVARCHAR2 (20),
"CUS_C_BILL_SUB_DISTRICT" NVARCHAR2 (20),
"CUS_C_BILL_ZIPCODE" VARCHAR2 (5),
"CUS_C_EMAIL" VARCHAR2 (20),
"CANCEL_REASON" VARCHAR2 (20),
"CANCEL_BY" VARCHAR2 (20),
"CANCEL_DATE" TIMESTAMP ,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_CAR_INSURANCE ADD CONSTRAINT PK_R_CAR_INSURANCE PRIMARY KEY (VEH_BRAND , VEH_VIN_NO ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_R_WS_MULTI_SOURCE_UNITS
-- ===============================
--

CREATE TABLE "TB_R_WS_MULTI_SOURCE_UNITS" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"UNIT_VOLUME" NUMBER (5),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 184995338K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_WS_MULTI_SOURCE_UNITS ADD CONSTRAINT PK_R_WS_MULTI_SOURCE_UNITS PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , VOLUME_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 184995338K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_WS_MULTI_SOURCE_UNITS1 on TB_R_WS_MULTI_SOURCE_UNITS (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL, UNIT_PLANT, UNIT_TYPE, UNIT_MODEL, VOLUME_MONTH)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 184995338K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_WS_PACKING_MOVEMENT
-- ===============================
--

CREATE TABLE "TB_R_WS_PACKING_MOVEMENT" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"PACKING_VOLUME" NUMBER (5),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 184995338K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_WS_PACKING_MOVEMENT ADD CONSTRAINT PK_R_WS_PACKING_MOVEMENT PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , VOLUME_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 184995338K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_WS_PACKING_MOVEMENT1 on TB_R_WS_PACKING_MOVEMENT (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL, UNIT_PLANT, UNIT_TYPE, UNIT_MODEL, VOLUME_MONTH)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 184995338K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_RUNDOWN_KOMPO_STS
-- ===============================
--

CREATE TABLE "TB_R_RUNDOWN_KOMPO_STS" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"UPLOAD_TYPE" VARCHAR2 (1) NOT NULL,
"UPLOAD_STS" VARCHAR2 (2),
"ROUND_FLAG" VARCHAR2 (1),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 205507K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_RUNDOWN_KOMPO_STS ADD CONSTRAINT PK_R_RUNDOWN_KOMPO_STS PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 205507K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_RUNDOWN_KOMPO_STS1 on TB_R_RUNDOWN_KOMPO_STS (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL, UNIT_PLANT, UNIT_TYPE, UNIT_MODEL)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 205507K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_PAMS_RUNDOWN
-- ===============================
--

CREATE TABLE "TB_R_PAMS_RUNDOWN" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"FILE_ID" VARCHAR2 (50) NOT NULL,
"FILE_NAME" VARCHAR2 (50) NOT NULL,
"IMPORTER" VARCHAR2 (5) NOT NULL,
"RUNDOWN_KEY" VARCHAR2 (70) NOT NULL,
"VARIATION" VARCHAR2 (10),
"SS_NO" VARCHAR2 (2),
"ID_LINE" VARCHAR2 (2),
"EXPORTER" VARCHAR2 (5) NOT NULL,
"ORDER_DT" DATE  NOT NULL,
"PROD_DT" DATE  NOT NULL,
"PROD_VOLUME" NUMBER (5) NOT NULL,
"LOCAL_STOCK" NUMBER (5) NOT NULL,
"STOCK_DAYS" NUMBER (4,2) NOT NULL,
"UNLOAD" NUMBER (5),
"TRANSIT" NUMBER (5),
"LOADING" NUMBER (5),
"PORT_STOCK" NUMBER (5),
"PACK_VOLUME" NUMBER (5) NOT NULL,
"LOT_SIZE" NUMBER (5),
"NO_OF_LOT" NUMBER (5),
"TOTAL_STOCK" NUMBER (5) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 48401910K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_PAMS_RUNDOWN ADD CONSTRAINT PK_R_PAMS_RUNDOWN PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , PROD_DT ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 48401910K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_R_KOMPO
-- ===============================
--

CREATE TABLE "TB_R_KOMPO" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"FILE_ID" VARCHAR2 (50) NOT NULL,
"FILE_NAME" VARCHAR2 (50) NOT NULL,
"IMPORTER" VARCHAR2 (5),
"RUNDOWN_KEY" VARCHAR2 (70),
"EXPORTER" VARCHAR2 (5) NOT NULL,
"ORDER_DT" DATE  NOT NULL,
"VANNING_VOLUME" NUMBER (5) NOT NULL,
"VANNING_DT" DATE  NOT NULL,
"LOADING_DT" DATE  NOT NULL,
"UNLOADING_DT" DATE  NOT NULL,
"PROD_DT" DATE  NOT NULL,
"PROD_VOLUME" NUMBER (5) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 89215386K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_KOMPO ADD CONSTRAINT PK_R_KOMPO PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , VANNING_DT , PROD_DT ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 89215386K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_R_KOMPO_VAN_RESULT
-- ===============================
--

CREATE TABLE "TB_R_KOMPO_VAN_RESULT" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"LOT_SIZE" NUMBER (3),
"VANNING_MONTH" VARCHAR2 (6) NOT NULL,
"VANNING_VOLUME" NUMBER (5) NOT NULL,
"ROUNDING_VOLUME" NUMBER (5),
"ADJUST_VOLUME" NUMBER (5),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 747602K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_KOMPO_VAN_RESULT ADD CONSTRAINT PK_R_KOMPO_VAN_RESULT PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , VANNING_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 747602K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_R_CAPA_RESULT
-- ===============================
--

CREATE TABLE "TB_R_CAPA_RESULT" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PARENT_LINE" VARCHAR2 (5) NOT NULL,
"INCOMING_VOL_STS" VARCHAR2 (2) NOT NULL,
"REMARK" VARCHAR2 (2),
"CONFIRMED_FLAG" VARCHAR2 (1) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 28672297K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_CAPA_RESULT ADD CONSTRAINT PK_R_CAPA_RESULT PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , UNIT_PARENT_LINE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 28672297K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_CAPA_RESULT1 on TB_R_CAPA_RESULT (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 28672297K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_R_CAPA_RESULT2 on TB_R_CAPA_RESULT (VERSION, GETSUDO_MONTH, TIMING, UNIT_PLANT, UNIT_PARENT_LINE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 28672297K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_MULTI_LINE_SPLITING
-- ===============================
--

CREATE TABLE "TB_R_MULTI_LINE_SPLITING" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_PARENT_LINE" VARCHAR2 (5) NOT NULL,
"UNIT_SUB_LINE" VARCHAR2 (5) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"SPLITING_VOLUME" NUMBER (5),
"SUB_LINE_CAPA_RESULT" VARCHAR2 (2),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 6984K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_R_MULTI_LINE_SPLITING ADD CONSTRAINT PK_R_MULTI_LINE_SPLITING PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , UNIT_PLANT , UNIT_PARENT_LINE , UNIT_SUB_LINE , UNIT_MODEL , VOLUME_MONTH ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 6984K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_R_MULTI_LINE_SPLITING1 on TB_R_MULTI_LINE_SPLITING (VERSION, GETSUDO_MONTH, TIMING, UNIT_PLANT, UNIT_PARENT_LINE)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 6984K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_S_CALENDAR
-- ===============================
--

CREATE TABLE "TB_S_CALENDAR" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"PLANT" VARCHAR2 (20),
"CALENDAR_DT" DATE ,
"CALENDAR_FLAG" VARCHAR2 (1),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_UNIT_PLANT_CAPA
-- ===============================
--

CREATE TABLE "TB_S_UNIT_PLANT_CAPA" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_PARENT_LINE" VARCHAR2 (5),
"UNIT_SUB_LINE" VARCHAR2 (5),
"UNIT_CAPA_MONTH" VARCHAR2 (6),
"MONTHLY_CAPA" NUMBER (5),
"DAILY_CAPA" NUMBER (5),
"WORKING_DAY" NUMBER (2),
"WORKING_TIME" NUMBER (3),
"WORKING_SHIFT" NUMBER (1),
"TAKT_TIME" NUMBER (4,2),
"EFFICIENCY" NUMBER (5,2),
"DAILY_OT" NUMBER (4,2),
"HOLIDAY_OT" NUMBER (2),
"SPECIAL_EFFORT" NUMBER (4),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_KAIKIENG
-- ===============================
--

CREATE TABLE "TB_S_KAIKIENG" (
"VERSION" VARCHAR2 (10),
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"VOLUME_MONTH" VARCHAR2 (6),
"VEHICLE_VOLUME" NUMBER (5),
"UNIT_TYPE" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"UNIT_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_WS_MULTI_SOURCE_UNITS
-- ===============================
--

CREATE TABLE "TB_S_WS_MULTI_SOURCE_UNITS" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"VOLUME_MONTH" VARCHAR2 (6),
"UNIT_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_WS_PACKING_MOVEMENT
-- ===============================
--

CREATE TABLE "TB_S_WS_PACKING_MOVEMENT" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_TYPE" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"VOLUME_MONTH" VARCHAR2 (6),
"PACKING_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_PAMS_RUNDOWN
-- ===============================
--

CREATE TABLE "TB_S_PAMS_RUNDOWN" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"FILE_ID" VARCHAR2 (50),
"FILE_NAME" VARCHAR2 (50),
"IMPORTER" VARCHAR2 (5),
"RUNDOWN_KEY" VARCHAR2 (70),
"VARIATION" VARCHAR2 (10),
"SS_NO" VARCHAR2 (2),
"ID_LINE" VARCHAR2 (2),
"EXPORTER" VARCHAR2 (5),
"ORDER_DT" DATE ,
"PROD_DT" DATE ,
"PROD_VOLUME" NUMBER (5),
"LOCAL_STOCK" NUMBER (5),
"STOCK_DAYS" NUMBER (4,2),
"UNLOAD" NUMBER (5),
"TRANSIT" NUMBER (5),
"LOADING" NUMBER (5),
"PORT_STOCK" NUMBER (5),
"PACK_VOLUME" NUMBER (5),
"LOT_SIZE" NUMBER (5),
"NO_OF_LOT" NUMBER (5),
"TOTAL_STOCK" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_KOMPO
-- ===============================
--

CREATE TABLE "TB_S_KOMPO" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"VEHICLE_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_MODEL" VARCHAR2 (30),
"FILE_ID" VARCHAR2 (50),
"FILE_NAME" VARCHAR2 (50),
"IMPORTER" VARCHAR2 (5),
"RUNDOWN_KEY" VARCHAR2 (70),
"EXPORTER" VARCHAR2 (5),
"ORDER_DT" DATE ,
"VANNING_VOLUME" NUMBER (5),
"VANNING_DT" DATE ,
"LOADING_DT" DATE ,
"UNLOADING_DT" DATE ,
"PROD_DT" DATE ,
"PROD_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_S_MULTI_LINE_SPLITING
-- ===============================
--

CREATE TABLE "TB_S_MULTI_LINE_SPLITING" (
"GETSUDO_MONTH" VARCHAR2 (6),
"TIMING" VARCHAR2 (4),
"UNIT_PLANT" VARCHAR2 (20),
"UNIT_PARENT_LINE" VARCHAR2 (5),
"UNIT_SUB_LINE" VARCHAR2 (5),
"UNIT_MODEL" VARCHAR2 (30),
"VOLUME_MONTH" VARCHAR2 (6),
"SPLITING_VOLUME" NUMBER (5),
"UPLOAD_FILE_NAME" VARCHAR2 (270),
"APL_ID" VARCHAR2 (10),
"RUNNING_NO" NUMBER (5),
"CREATE_BY" VARCHAR2 (20))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_P_KAIKIENG_H
-- ===============================
--

CREATE TABLE "TB_P_KAIKIENG_H" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"VEHICLE_VOLUME" NUMBER (5),
"KAIKIENG_FILE_NAME" VARCHAR2 (270),
"WORKSHEET_FILE_NAME" VARCHAR2 (270),
"SUBMIT_DT" DATE ,
"REJECT_DT" DATE ,
"KAIKIENG_STATUS" VARCHAR2 (2) NOT NULL,
"WORKSHEET_STATUS" VARCHAR2 (2),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_P_KAIKIENG_H ADD CONSTRAINT PK_P_KAIKIENG_H PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , VOLUME_MONTH , CREATE_BY ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_P_KAIKIENG_D
-- ===============================
--

CREATE TABLE "TB_P_KAIKIENG_D" (
"VERSION" VARCHAR2 (10) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_TYPE" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"VOLUME_MONTH" VARCHAR2 (6) NOT NULL,
"UNIT_VOLUME" NUMBER (5),
"MULTI_SOURCE_FLAG" VARCHAR2 (1) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_P_KAIKIENG_D ADD CONSTRAINT PK_P_KAIKIENG_D PRIMARY KEY (VERSION , GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_MODEL , VOLUME_MONTH , CREATE_BY ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_P_KAIKIENG_D1 on TB_P_KAIKIENG_D (VERSION, GETSUDO_MONTH, TIMING, VEHICLE_PLANT, VEHICLE_MODEL, UNIT_TYPE, UNIT_MODEL, VOLUME_MONTH)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 64K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_L_UPLOAD_STS
-- ===============================
--

CREATE TABLE "TB_L_UPLOAD_STS" (
"UPLOAD_TYPE" VARCHAR2 (20) NOT NULL,
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20),
"UNIT_PLANT" VARCHAR2 (20),
"VEHICLE_MODEL" VARCHAR2 (30),
"UNIT_MODEL" VARCHAR2 (30),
"UNIT_PARENT_LINE" VARCHAR2 (10),
"UNIT_SUB_LINE" VARCHAR2 (10),
"FILE_NAME" VARCHAR2 (270),
"MODULE_ID" VARCHAR2 (10),
"FUNCTION_ID" VARCHAR2 (10),
"APL_ID" VARCHAR2 (10),
"STATUS" VARCHAR2 (1) NOT NULL,
"MESSAGE" VARCHAR2 (100) NOT NULL,
"TRANS_UPDATE_DT" TIMESTAMP ,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 604K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_L_UPLOAD_STS ADD CONSTRAINT PK_L_UPLOAD_STS PRIMARY KEY (APL_ID ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 604K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_L_UPLOAD_DETAIL
-- ===============================
--

CREATE TABLE "TB_L_UPLOAD_DETAIL" (
"GETSUDO_MONTH" VARCHAR2 (6) NOT NULL,
"TIMING" VARCHAR2 (4) NOT NULL,
"VEHICLE_PLANT" VARCHAR2 (20) NOT NULL,
"VEHICLE_MODEL" VARCHAR2 (30) NOT NULL,
"UNIT_PLANT" VARCHAR2 (20) NOT NULL,
"UNIT_MODEL" VARCHAR2 (30) NOT NULL,
"ERROR_SHEET" VARCHAR2 (1) NOT NULL,
"RUNNING_NO" NUMBER (5) NOT NULL,
"ERROR_DATE" VARCHAR2 (10),
"ERROR_MONTH" VARCHAR2 (6),
"ERROR_RUNDOWN" VARCHAR2 (20),
"ERROR_CALENDAR" VARCHAR2 (20),
"ERROR_WORKSHEET" NUMBER (5),
"ERROR_STOCK_MIN" NUMBER (4,2),
"ERROR_STOCK_MAX" NUMBER (4,2),
"APL_ID" VARCHAR2 (10) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 36833K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_L_UPLOAD_DETAIL ADD CONSTRAINT PK_L_UPLOAD_DETAIL PRIMARY KEY (GETSUDO_MONTH , TIMING , VEHICLE_PLANT , VEHICLE_MODEL , UNIT_PLANT , UNIT_MODEL , ERROR_SHEET , RUNNING_NO ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 36833K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_L_UPLOAD_DETAIL1 on TB_L_UPLOAD_DETAIL (APL_ID)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 36833K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_L_LOGGER
-- ===============================
--

CREATE TABLE "TB_L_LOGGER" (
"D_HODTCRE" DATE  NOT NULL,
"N_SEQ_NO" NUMBER (9) NOT NULL,
"V_APL_ID" VARCHAR2 (10),
"V_MODULE_ID" VARCHAR2 (10) NOT NULL,
"V_FUNCTION_ID" VARCHAR2 (10) NOT NULL,
"V_USERCRE" VARCHAR2 (20) NOT NULL,
"V_MESSAGE_TYPE" VARCHAR2 (1) NOT NULL,
"V_MESSAGE_CODE" VARCHAR2 (12),
"V_MESSAGE" VARCHAR2 (2000) NOT NULL,
"V_STATUS" VARCHAR2 (1))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 1926175K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_L_LOGGER ADD CONSTRAINT PK_L_LOGGER PRIMARY KEY (N_SEQ_NO ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 1926175K 
NEXT 16384K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_MODULE_H
-- ===============================
--

CREATE TABLE "TB_M_MODULE_H" (
"V_MODULE_ID" VARCHAR2 (10) NOT NULL,
"V_MODULE_NAME" VARCHAR2 (100),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_MODULE_H ADD CONSTRAINT PK_M_MODULE_H PRIMARY KEY (V_MODULE_ID ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_MODULE_D
-- ===============================
--

CREATE TABLE "TB_M_MODULE_D" (
"V_MODULE_ID" VARCHAR2 (10) NOT NULL,
"V_FUNCTION_ID" VARCHAR2 (10) NOT NULL,
"V_FUNCTION_NAME" VARCHAR2 (100),
"V_ERROR_FLAG" CHAR (1),
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_MODULE_D ADD CONSTRAINT PK_M_MODULE_D PRIMARY KEY (V_MODULE_ID , V_FUNCTION_ID ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_SYSTEM
-- ===============================
--

CREATE TABLE "TB_M_SYSTEM" (
"CATEGORY" VARCHAR2 (40) NOT NULL,
"SUB_CATEGORY" VARCHAR2 (40) NOT NULL,
"CD" VARCHAR2 (40) NOT NULL,
"VALUE" VARCHAR2 (200) NOT NULL,
"REMARK" VARCHAR2 (200),
"STATUS" VARCHAR2 (1) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 92K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_SYSTEM ADD CONSTRAINT PK_M_SYSTEM PRIMARY KEY (CATEGORY , SUB_CATEGORY , CD ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 92K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

CREATE INDEX IX_M_SYSTEM1 on TB_M_SYSTEM (CATEGORY, SUB_CATEGORY, CD, VALUE, STATUS)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 92K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
CREATE INDEX IX_M_SYSTEM2 on TB_M_SYSTEM (CATEGORY, SUB_CATEGORY, STATUS)
TABLESPACE TBSP_INDEX00
STORAGE ( 
INITIAL 92K 
NEXT 64K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--
-- Creating table TB_R_BATCH_PARAMETER
-- ===============================
--

CREATE TABLE "TB_R_BATCH_PARAMETER" (
"PARAM_ID" VARCHAR2 (6),
"REQUEST_ID" VARCHAR2 (8),
"BATCH_ID" VARCHAR2 (10),
"PARAMETERS" VARCHAR2 (4000),
"PROJECT_CODE" CHAR (3),
"SUPPORT_ID" VARCHAR2 (10),
"REQUEST_BY" VARCHAR2 (20),
"REQUEST_DT" TIMESTAMP  NOT NULL)
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 19077K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_R_BATCH_QUEUE
-- ===============================
--

CREATE TABLE "TB_R_BATCH_QUEUE" (
"QUEUE_NO" NUMBER (22,0),
"REQUEST_ID" VARCHAR2 (8),
"BATCH_ID" VARCHAR2 (10),
"REQUEST_DATE" DATE ,
"REQUEST_BY" VARCHAR2 (10),
"PARAMETERS" VARCHAR2 (4000),
"SUPPORT_ID" VARCHAR2 (10),
"PROJECT_CODE" CHAR (3),
"DESCRIPTION" VARCHAR2 (200),
"APP_ID" VARCHAR2 (10))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 32799K 
NEXT 5120K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);


--
-- Creating table TB_M_SEQ
-- ===============================
--

CREATE TABLE "TB_M_SEQ" (
"SEQ_CODE" VARCHAR2 (20) NOT NULL,
"SEQ_KEY" VARCHAR2 (10) NOT NULL,
"CURRENT_VALUE" NUMBER (10,0) NOT NULL,
"START_VALUE" NUMBER (10,0) NOT NULL,
"DOC_NO_FORMAT" VARCHAR2 (50) NOT NULL,
"START_MONTH" NUMBER (2,0) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL,
"VERSION" NUMBER (10,0))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_SEQ ADD CONSTRAINT PK_M_SEQ PRIMARY KEY (SEQ_CODE ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

--
-- Creating table TB_M_HIST_SEQ
-- ===============================
--

CREATE TABLE "TB_M_HIST_SEQ" (
"SEQ_CODE" VARCHAR2 (20) NOT NULL,
"SEQ_KEY" VARCHAR2 (10) NOT NULL,
"CURRENT_VALUE" NUMBER (10,0) NOT NULL,
"START_VALUE" NUMBER (10,0) NOT NULL,
"DOC_NO_FORMAT" VARCHAR2 (50) NOT NULL,
"START_MONTH" NUMBER (2,0) NOT NULL,
"CREATE_BY" VARCHAR2 (20) NOT NULL,
"CREATE_DT" TIMESTAMP  NOT NULL,
"UPDATE_BY" VARCHAR2 (20) NOT NULL,
"UPDATE_DT" TIMESTAMP  NOT NULL,
"HISTORY_KEY" VARCHAR2 (10) NOT NULL,
"VERSION" NUMBER (10,0))
TABLESPACE TBSP_USER00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

ALTER TABLE TB_M_HIST_SEQ ADD CONSTRAINT PK_M_HIST_SEQ PRIMARY KEY (SEQ_CODE , HISTORY_KEY ) 
USING INDEX TABLESPACE TBSP_INDEX00
PCTFREE 10 
INITRANS 2 
MAXTRANS 255
STORAGE ( 
INITIAL 64K 
NEXT 1K 
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);

